# Modified from https://github.com/tauri-apps/tauri-action
name: "Build for Release"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Ubuntu-only stuff
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0 jq
        # Overwrite tauri.conf.json so the only icons listed are PNGs, to make the build work on Ubuntu
        cat src-tauri\tauri.conf.json | jq '.tauri.bundle.icon = ["icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png"]' | tee src-tauri/tauri.conf.json > /dev/null
    - name: Install Node dependencies
      run: |
        yarn
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false